name: Static tests

on: [push, pull_request_target]

jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run unit tests
        run: make unit-test

  static:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run static linters
        run: make static
